[package]
name = "r_chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.0.0"
strum = "0.15.0"
strum_macros = "0.15.0"
thiserror = "1.0"
